# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: p4/bm/dataplane_interface.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='p4/bm/dataplane_interface.proto',
  package='p4.bm',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1fp4/bm/dataplane_interface.proto\x12\x05p4.bm\"R\n\x13PacketStreamRequest\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x11\n\tdevice_id\x18\x02 \x01(\x04\x12\x0c\n\x04port\x18\x03 \x01(\r\x12\x0e\n\x06packet\x18\x04 \x01(\x0c\"S\n\x14PacketStreamResponse\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x11\n\tdevice_id\x18\x02 \x01(\x04\x12\x0c\n\x04port\x18\x03 \x01(\r\x12\x0e\n\x06packet\x18\x04 \x01(\x0c\"g\n\x18SetPortOperStatusRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\x04\x12\x0c\n\x04port\x18\x02 \x01(\r\x12*\n\x0boper_status\x18\x03 \x01(\x0e\x32\x15.p4.bm.PortOperStatus\"\x1b\n\x19SetPortOperStatusResponse*S\n\x0ePortOperStatus\x12\x17\n\x13OPER_STATUS_UNKNOWN\x10\x00\x12\x14\n\x10OPER_STATUS_DOWN\x10\x01\x12\x12\n\x0eOPER_STATUS_UP\x10\x02\x32\xbd\x01\n\x12\x44\x61taplaneInterface\x12M\n\x0cPacketStream\x12\x1a.p4.bm.PacketStreamRequest\x1a\x1b.p4.bm.PacketStreamResponse\"\x00(\x01\x30\x01\x12X\n\x11SetPortOperStatus\x12\x1f.p4.bm.SetPortOperStatusRequest\x1a .p4.bm.SetPortOperStatusResponse\"\x00\x62\x06proto3')
)

_PORTOPERSTATUS = _descriptor.EnumDescriptor(
  name='PortOperStatus',
  full_name='p4.bm.PortOperStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OPER_STATUS_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPER_STATUS_DOWN', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPER_STATUS_UP', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=345,
  serialized_end=428,
)
_sym_db.RegisterEnumDescriptor(_PORTOPERSTATUS)

PortOperStatus = enum_type_wrapper.EnumTypeWrapper(_PORTOPERSTATUS)
OPER_STATUS_UNKNOWN = 0
OPER_STATUS_DOWN = 1
OPER_STATUS_UP = 2



_PACKETSTREAMREQUEST = _descriptor.Descriptor(
  name='PacketStreamRequest',
  full_name='p4.bm.PacketStreamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='p4.bm.PacketStreamRequest.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='p4.bm.PacketStreamRequest.device_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='p4.bm.PacketStreamRequest.port', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packet', full_name='p4.bm.PacketStreamRequest.packet', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=124,
)


_PACKETSTREAMRESPONSE = _descriptor.Descriptor(
  name='PacketStreamResponse',
  full_name='p4.bm.PacketStreamResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='p4.bm.PacketStreamResponse.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='p4.bm.PacketStreamResponse.device_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='p4.bm.PacketStreamResponse.port', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='packet', full_name='p4.bm.PacketStreamResponse.packet', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=209,
)


_SETPORTOPERSTATUSREQUEST = _descriptor.Descriptor(
  name='SetPortOperStatusRequest',
  full_name='p4.bm.SetPortOperStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='device_id', full_name='p4.bm.SetPortOperStatusRequest.device_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='p4.bm.SetPortOperStatusRequest.port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='oper_status', full_name='p4.bm.SetPortOperStatusRequest.oper_status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=314,
)


_SETPORTOPERSTATUSRESPONSE = _descriptor.Descriptor(
  name='SetPortOperStatusResponse',
  full_name='p4.bm.SetPortOperStatusResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=343,
)

_SETPORTOPERSTATUSREQUEST.fields_by_name['oper_status'].enum_type = _PORTOPERSTATUS
DESCRIPTOR.message_types_by_name['PacketStreamRequest'] = _PACKETSTREAMREQUEST
DESCRIPTOR.message_types_by_name['PacketStreamResponse'] = _PACKETSTREAMRESPONSE
DESCRIPTOR.message_types_by_name['SetPortOperStatusRequest'] = _SETPORTOPERSTATUSREQUEST
DESCRIPTOR.message_types_by_name['SetPortOperStatusResponse'] = _SETPORTOPERSTATUSRESPONSE
DESCRIPTOR.enum_types_by_name['PortOperStatus'] = _PORTOPERSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PacketStreamRequest = _reflection.GeneratedProtocolMessageType('PacketStreamRequest', (_message.Message,), dict(
  DESCRIPTOR = _PACKETSTREAMREQUEST,
  __module__ = 'p4.bm.dataplane_interface_pb2'
  # @@protoc_insertion_point(class_scope:p4.bm.PacketStreamRequest)
  ))
_sym_db.RegisterMessage(PacketStreamRequest)

PacketStreamResponse = _reflection.GeneratedProtocolMessageType('PacketStreamResponse', (_message.Message,), dict(
  DESCRIPTOR = _PACKETSTREAMRESPONSE,
  __module__ = 'p4.bm.dataplane_interface_pb2'
  # @@protoc_insertion_point(class_scope:p4.bm.PacketStreamResponse)
  ))
_sym_db.RegisterMessage(PacketStreamResponse)

SetPortOperStatusRequest = _reflection.GeneratedProtocolMessageType('SetPortOperStatusRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETPORTOPERSTATUSREQUEST,
  __module__ = 'p4.bm.dataplane_interface_pb2'
  # @@protoc_insertion_point(class_scope:p4.bm.SetPortOperStatusRequest)
  ))
_sym_db.RegisterMessage(SetPortOperStatusRequest)

SetPortOperStatusResponse = _reflection.GeneratedProtocolMessageType('SetPortOperStatusResponse', (_message.Message,), dict(
  DESCRIPTOR = _SETPORTOPERSTATUSRESPONSE,
  __module__ = 'p4.bm.dataplane_interface_pb2'
  # @@protoc_insertion_point(class_scope:p4.bm.SetPortOperStatusResponse)
  ))
_sym_db.RegisterMessage(SetPortOperStatusResponse)



_DATAPLANEINTERFACE = _descriptor.ServiceDescriptor(
  name='DataplaneInterface',
  full_name='p4.bm.DataplaneInterface',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=431,
  serialized_end=620,
  methods=[
  _descriptor.MethodDescriptor(
    name='PacketStream',
    full_name='p4.bm.DataplaneInterface.PacketStream',
    index=0,
    containing_service=None,
    input_type=_PACKETSTREAMREQUEST,
    output_type=_PACKETSTREAMRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetPortOperStatus',
    full_name='p4.bm.DataplaneInterface.SetPortOperStatus',
    index=1,
    containing_service=None,
    input_type=_SETPORTOPERSTATUSREQUEST,
    output_type=_SETPORTOPERSTATUSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATAPLANEINTERFACE)

DESCRIPTOR.services_by_name['DataplaneInterface'] = _DATAPLANEINTERFACE

# @@protoc_insertion_point(module_scope)
