# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from p4.server.v1 import config_pb2 as p4_dot_server_dot_v1_dot_config__pb2


class ServerConfigStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Set = channel.unary_unary(
        '/p4.server.v1.ServerConfig/Set',
        request_serializer=p4_dot_server_dot_v1_dot_config__pb2.SetRequest.SerializeToString,
        response_deserializer=p4_dot_server_dot_v1_dot_config__pb2.SetResponse.FromString,
        )
    self.Get = channel.unary_unary(
        '/p4.server.v1.ServerConfig/Get',
        request_serializer=p4_dot_server_dot_v1_dot_config__pb2.GetRequest.SerializeToString,
        response_deserializer=p4_dot_server_dot_v1_dot_config__pb2.GetResponse.FromString,
        )


class ServerConfigServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Set(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ServerConfigServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Set': grpc.unary_unary_rpc_method_handler(
          servicer.Set,
          request_deserializer=p4_dot_server_dot_v1_dot_config__pb2.SetRequest.FromString,
          response_serializer=p4_dot_server_dot_v1_dot_config__pb2.SetResponse.SerializeToString,
      ),
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=p4_dot_server_dot_v1_dot_config__pb2.GetRequest.FromString,
          response_serializer=p4_dot_server_dot_v1_dot_config__pb2.GetResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'p4.server.v1.ServerConfig', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
