BMV2_SWITCH_EXE = /home/p4/Documents/behavioral-model/targets/simple_switch_grpc/simple_switch_grpc
TOPO = topologies/mesh/topology.json

CONFIGURE_SCRIPT = configuration/configure_p4switch_json.py
DEFAULT_P4_SRC = main_static.p4

include ../utils/Makefile
