BMV2_SWITCH_EXE = simple_switch_grpc
TOPO = topologies/mesh_topology/topology.json

CONFIGURE_SCRIPT = python_scripts/configuration/configure_json.py
DEFAULT_P4_SRC = main_static.p4
TEST_JSON = ../tests/static_test.json

include ../utils/Makefile
