BMV2_SWITCH_EXE = simple_switch_grpc
TOPO = topologies/mesh/topology.json

CONFIGURE_SCRIPT = ../testing/python_scripts/configuration/configure_json.py
DEFAULT_P4_SRC = main_static.p4

include ../utils/Makefile
